[api]
port = 3001

[worker]
minShips = 5
minEnergyNodes = 5

[database]
host = "172.17.0.4"
port = 3306
username = "root"
password = "test"
db = "game"

[web]
endpoints = ["http://localhost:9000"]
username = "web"
password = "wasm-space-program"
db = "game"
