[api]
port = 3001

[database]
host = "127.0.0.1"
port = 3306
username = "root"
password = "test"
db = "game"

[web]
endpoints = ["http://127.0.0.1:9000", "http://127.0.0.1:9000"]
username = "web"
password = "wasm-space-program"
db = "game"
