[api]
port = 3001

[database_primary]
hosts = ["127.0.0.1"]
port = 3306
username = "root"
password = "test"
name = "game"

[database_secondary]
hosts = ["127.0.0.1"]
port = 3306
username = "web"
password = "wasm-space-program"
name = "game"
