[api]
port = 3001

[database]
host = "127.0.0.1"
port = 3306
username = "root"
password = "test"
db = "game"

[web]
endpoints = ["127.0.0.1:8080"]
username = "web"
password = "wasm-space-program"
db = "game"
