name: on push
on: [push]
jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install & cache web dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: web

      - name: Format
        run: yarn prettier --check .
        working-directory: web

      - name: Lint
        run: yarn eslint
        working-directory: web

      - name: Check typescript
        run: yarn run tsc
        working-directory: web

      - name: Build
        run: yarn run vite build
        working-directory: web

  agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          components: rustfmt, rust-src, clippy
          target: wasm32-wasi

      - name: Clippy
        run: cargo clippy
        working-directory: agent

      - name: Format
        run: cargo fmt --check
        working-directory: agent

      - name: Build
        run: cargo build --release --target wasm32-wasi
        working-directory: agent

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Build
        run: go build
        working-directory: backend
