name: on push
on: [push]
jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install & cache web dependencies
        uses: bahmutov/npm-install@v1

      - name: Check typescript
        run: yarn run tsc

      - name: Build
        run: yarn run vite build

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: dist

  agent:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: agent

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          components: rustfmt, rust-src, clippy
          target: wasm32-wasi

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

      - uses: actions-rs/cargo@v1
        with:
          command: wasi
          args: build --release

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Build
        run: go build

      - name: Install fly
        if: github.ref == 'refs/heads/main'
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only
